ci:
    autoupdate_schedule: quarterly
    autoupdate_commit_msg: 'Bump `pre-commit` Hooks to Latest Versions'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.8.6'
    hooks:
      - id: ruff
        name: ruff
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - --diff
          - --check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: mypy
        files: ^(?!(tests)).*\.py$
        args:
          - --install-types
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
